version: '3.8'

services:
  latex:
    build: .
    volumes:
      - ./src:/workspace/src
      - ./.textlintrc.json:/workspace/.textlintrc.json
      - ./.textlintrc.prh.yml:/workspace/.textlintrc.prh.yml

    working_dir: /workspace

  build:
    extends: latex
    command: >
      bash -c "
        cd src &&
        mkdir -p output &&
        uplatex -interaction=nonstopmode main.tex &&
        uplatex -interaction=nonstopmode main.tex &&
        dvipdfmx main.dvi &&
        mv main.pdf output/main.pdf
      "

  clean:
    extends: latex
    command: >
      bash -c "
        cd src &&
        rm -f *.aux *.log *.dvi *.toc *.out *.synctex.gz *.fls *.fdb_latexmk *.bbl *.blg
      "

  textlint:
   extends: latex
   command: >
     bash -c "
       find src -name '*.tex' ! -name 'title.tex' -print0 | xargs -0 textlint
     "

  fmt:
    extends: latex
    command: >
      bash -c "
        find src -name '*.tex' ! -name 'title.tex' -print0 | xargs -0 textlint --fix
      "