name: textlint Check

on:
  pull_request:
    paths:
      - 'src/**/*.tex'
      - '.textlintrc.json'
      - '.textlintrc.prh.yml'
  workflow_dispatch:

jobs:
  textlint:
    name: Run textlint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install textlint
        run: |
          npm install -g \
            textlint \
            textlint-rule-preset-ja-technical-writing \
            textlint-rule-prh \
            textlint-rule-preset-ja-spacing \
            textlint-rule-spellcheck-tech-word

      - name: Run textlint
        id: textlint
        run: |
          textlint src/**/*.tex > textlint-result.txt 2>&1 || echo "error=true" >> $GITHUB_OUTPUT
          cat textlint-result.txt

      - name: Create summary
        if: always()
        run: |
          if [ "${{ steps.textlint.outputs.error }}" == "true" ]; then
            echo "## ❌ textlint Check Failed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "以下の問題が見つかりました:" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat textlint-result.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "## ✅ textlint Check Passed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "文章チェックが正常に完了しました。" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Comment PR
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const result = fs.readFileSync('textlint-result.txt', 'utf8');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## ❌ textlint Check Failed\n\n文章に問題が見つかりました:\n\n\`\`\`\n${result}\n\`\`\`\n\n修正するには、ローカルで \`make fmt\` を実行してください。`
            });